name = "pixland-worker"
main = "src/index.ts"
compatibility_date = "2022-06-10"
account_id = "b6754402d59fc29ee8b62119014fec89"
route = "worker.pixland.pwp.app/*"

[[r2_buckets]]
binding = 'pixland'
bucket_name = 'pixland'
preview_bucket_name = 'pixland-dev'
