name = "pixland-worker"
main = "src/index.ts"
compatibility_date = "2022-06-10"
account_id = "YOUR_ACCOUNT_ID"
route = "ROUTE"

[[r2_buckets]]
binding = 'pixland'
bucket_name = 'pixland'
preview_bucket_name = 'pixland-dev'
